__version__ = "0.1.0rc0"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/TopLevel.ipynb.

# %% auto 0
__all__ = ['dummy']

# %% ../nbs/TopLevel.ipynb 1
from ._components.mono_dense_layer import MonoDense

# %% ../nbs/TopLevel.ipynb 2
def dummy() -> None:
    pass


dummy.__module__ = "_dummy"

# %% ../nbs/TopLevel.ipynb 3
__all__ = ["MonoDense"]
