__version__ = "0.0.6rc1"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/TopLevel.ipynb.

# %% auto 0
__all__ = ['dummy']

# %% ../nbs/TopLevel.ipynb 1
from mono_dense_keras._components.mono_dense_layer import (
    MonoDense,
    replace_kernel_using_monotonicity_indicator,
)

# %% ../nbs/TopLevel.ipynb 2
def dummy() -> None:
    pass


dummy.__module__ = "_dummy"

# %% ../nbs/TopLevel.ipynb 3
__all__ = ["MonoDense", "replace_kernel_using_monotonicity_indicator"]
