# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mono-dense-keras',
                'doc_host': 'https://airtai.github.io',
                'git_url': 'https://github.com/airtai/mono-dense-keras',
                'lib_path': 'mono_dense_keras'},
  'syms': {'mono_dense_keras.core': {'mono_dense_keras.core.foo': ('core.html#foo', 'mono_dense_keras/core.py')}}}