project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "mono-dense-keras"
  site-url: "https://airtai.github.io/mono-dense-keras"
  description: "Monotonic Dense Layer implemented in Keras"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/airtai/mono-dense-keras"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/airtai/mono-dense-keras"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
