# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mono-dense-keras',
                'doc_host': 'https://airtai.github.io',
                'git_url': 'https://github.com/airtai/mono-dense-keras',
                'lib_path': 'airt'},
  'syms': { 'airt.keras.layers': { 'airt.keras.layers.MonotonicDense': ('layers.html#monotonicdense', 'airt/keras/layers.py'),
                                   'airt.keras.layers.MonotonicDense.__init__': ('layers.html#__init__', 'airt/keras/layers.py'),
                                   'airt.keras.layers.MonotonicDense.build': ('layers.html#build', 'airt/keras/layers.py'),
                                   'airt.keras.layers.MonotonicDense.call': ('layers.html#call', 'airt/keras/layers.py'),
                                   'airt.keras.layers.MonotonicDense.get_activation_selector': ( 'layers.html#get_activation_selector',
                                                                                                 'airt/keras/layers.py'),
                                   'airt.keras.layers.MonotonicDense.replace_kernel': ( 'layers.html#replace_kernel',
                                                                                        'airt/keras/layers.py')}}}