# Site
site_name: mono-dense-keras
site_url: https://airtai.github.io/mono-dense-keras
site_author: AIRT Technologies d.o.o.
site_description: Monotonic Dense Layer implemented in Keras

# Repository
repo_name: mono-dense-keras
repo_url: https://github.com/airtai/mono-dense-keras
edit_uri: ''

copyright: 2022 onwards, AIRT Technologies d.o.o.

docs_dir: docs
site_dir: site

plugins:
- literate-nav:
    nav_file: SUMMARY.md
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          heading_level: 2
          show_category_heading: true
          show_root_heading: true
          show_root_toc_entry: true
          show_signature_annotations: true
          show_if_no_docstring: true

markdown_extensions:
- pymdownx.arithmatex:
    generic: true
- pymdownx.inlinehilite
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.highlight:
    linenums: false
- pymdownx.snippets:
    check_paths: true
- pymdownx.tabbed:
    alternate_style: true
- admonition
- toc:
    permalink: ¤
#     - callouts
theme:
  name: material
  custom_dir: site_overrides
  features:
  - navigation.instant
#     - navigation.tabs
#     - navigation.tabs.sticky
#     - navigation.sections
#     - navigation.expand
  - navigation.indexes
  - navigation.top
#     - toc.integrates
  - search.suggest
  - search.highlight
  - search.share
  palette:
  - scheme: slate
    primary: black
    accent: yellow
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: default
    primary: black   # deep orange
    accent: red
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
#     repo: fontawesome/brands/gitlab
    logo: material/compass-outline
#     admonition:
#         <type>: <icon> 
  favicon: overrides/images/compass-outline.png

extra_css:
- overrides/css/extra.css

extra_javascript:
- overrides/js/extra.js
- overrides/js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social_image: https://oaidalleapiprodscus.blob.core.windows.net/private/org-gsdtNvd94nodt5ugz07WKGII/user-lmQiHK525wChMVvE3CPqCMHy/img-h4vz4C1Ji213G973dgNXzJAa.png?st=2022-12-13T11%3A34%3A35Z&se=2022-12-13T13%3A34%3A35Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2022-12-13T10%3A49%3A04Z&ske=2022-12-14T10%3A49%3A04Z&sks=b&skv=2021-08-06&sig=a%2BYaI9T6t4hW%2BS5zCP0OKvz1g4KP8YkGYCLoSOeX7Kw%3D
